import { useEffect, useRef, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [userInput, setUserInput] = useState(false);
  const [apiResponse, setAPIResponse] = useState(false);
  const textInput = useRef(null);

  const buttonOnClickHandler = () => {
    setUserInput(textInput.current.value);
  };

  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch("/api/", {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify(userInput),
      });
      setAPIResponse(await res.json());
    };
    fetchData().catch(console.error);
  }, [userInput]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Async user action</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
          <h1 className={styles.title}>Async user action</h1>
          <div
            style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}
          >
            <label htmlFor="input">User Input</label>
            <input ref={textInput} type="text" id="input" />
          </div>
          <button
            style={{ fontSize: "1.25rem", padding: "1rem", marginTop: "1rem" }}
            onClick={buttonOnClickHandler}
          >
            User action
          </button>
          {apiResponse && (
            <div
              style={{
                background: "black",
                color: "white",
                marginTop: "1rem",
                width: "auto",
                padding: "1rem",
              }}
            >
              <pre>{JSON.stringify(apiResponse)}</pre>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
